import os

CLOUDINARY_CLOUD_NAME = os.environ['CLOUDINARY_CLOUD_NAME']
CLOUDINARY_API_KEY = os.environ['CLOUDINARY_API_KEY']
CLOUDINARY_API_SECRET = os.environ['CLOUDINARY_API_SECRET']

SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
